branches:
  only:
  - master
  - preprod
  - prod
env:
- BRANCH=$TRAVIS_BRANCH MESSAGE=$TRAVIS_COMMIT_MESSAGE TAG=$TRAVIS_TAG AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
before_install:
- echo $AUTHOR_NAME
script:
- |
  if [ $AUTHOR_NAME = "Build Condition" ]; then
  echo $AUTHOR_NAME" success"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  elif [ $TRAVIS_BRANCH = preprod ]; then
  echo "such a shame, preprod"
  else
  echo "master"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  fi
