branches:
  only:
  - master
  - prod
env:
- BRANCH=$TRAVIS_BRANCH MESSAGE=$TRAVIS_COMMIT_MESSAGE TAG=$TRAVIS_TAG
script:
- |
  if [ $TRAVIS_TAG = prod ]; then
  echo "1"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  else
  echo "0"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  fi
