branches:
  only:
  - master
  - prod
language: node_js
node_js:
- "17"
services:
- docker
env:
- BRANCH=$TRAVIS_BRANCH MESSAGE=$TRAVIS_COMMIT_MESSAGE TAG=$TRAVIS_TAG
script:
- |
  if [ $TRAVIS_TAG = prod ]; then
  echo "1"
  else
  echo "0"
  fi
