branches:
  only:
  - master
  - preprod
  - prod
env:
- BRANCH=$TRAVIS_BRANCH MESSAGE=$TRAVIS_COMMIT_MESSAGE TAG=$TRAVIS_TAG
script:
- |
  if [ $TRAVIS_TAG = prod ]; then
  echo "prod"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  elif [ $TRAVIS_BRANCH = preprod ]; then
  echo "randomphrase"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  else
  echo "master"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  fi
