branches:
  only:
  - master
  - preprod
  - prod
env:
- BRANCH=$TRAVIS_BRANCH MESSAGE=$TRAVIS_COMMIT_MESSAGE TAG=$TRAVIS_TAG
script:
export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
echo $AUTHOR_NAME
- |
  if [ $TRAVIS_TAG = prod ]; then
  echo "1"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  elif [ $TRAVIS_BRANCH = preprod ]; then
  echo "randomphrase"
  else
  echo "0"
  echo $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE $TRAVIS_TAG
  fi
